### ISSUE TITLE
HTTP OTA is not working

### ISSUE THREAD

**Issue by OSapar** [FrancMunoz/electrontcpfirmflash#1]
Hi,

I have used the same code and tried to download file from my server but i couldn't. The firmware was downloaded completely but while launching it showed error. I have tested the code that I am trying to update over OTA.  Its showing the status as completed but again the same code of OTA executes and it tries to download file again. 
Check the below images.
![output](https://user-images.githubusercontent.com/41289433/63158616-44b5a500-c037-11e9-8382-9388a09640fb.png)
![code](https://user-images.githubusercontent.com/41289433/63158632-4aab8600-c037-11e9-9307-b36c1db29709.png)

**Comment by FrancMunoz** [comment]
Hi! I see it's failing while executing `Spark_Finish_Firmware_Update` I tested with **0.8.0rc10**, could you please tell me which version are you using? I guess you are using an electron, isn't it? 

Also, It fails when images aren't from the same version. Maybe Particle team has made some changes... but first, could you please provide the information requested?

**Comment by OSapar** [comment]
I am using electron with 1.2.1 . And I tried to download your firmware on my electron, its getting updated successfully. Then I uploaded your image on my server and tried but the problem is still there.

**Comment by FrancMunoz** [comment]
Sorry, I can't understand you clearly... If you upgrade from my server it works... but when you try from your server it fails... is that what you mean?

**Comment by OSapar** [comment]
Yes @FrancMunoz. I downloaded bin file from your server (www.zeroworks.net) )and placed it in my server (omtest2.000webhostapp.com) then I tried to upgrade electron, but it fails.

**Comment by FrancMunoz** [comment]
I compared two files downloaded from both servers and are identical. If you leave original code to download from my server:

```
    const char *host="www.zeroworks.net";
    const char *path="/updates/ota/flash.bin";
```

does it work? In a few days I will update one particle to latest version and try... meanwhile If you help me doing some tests will be nice.

If it works... could you please attach all the headers from HTTP?

**Comment by OSapar** [comment]
Yes, It worked for me. 

Header from zeroworks.net server
`Header:HTTP/1.1 200 OK
Content-Type: application/octet-stream
Last-Modified: Sun, 24 Feb 2019 12:00:54 GMT
Accept-Ranges: bytes
Server: Microsoft-IIS/8.0
X-Frame-Options: SAMEORIGIN
Date: Fri, 16 Aug 2019 06:10:31 GMT
Connection: close
Content-Length: 4172`

Headers from omtest2.000webhostapp server
`Header:HTTP/1.1 200 OK
Date: Fri, 16 Aug 2019 06:20:27 GMT
Content-Type: application/octet-stream
Content-Length: 4172
Connection: close
Last-Modified: Wed, 14 Aug 2019 12:28:04 GMT
Accept-Ranges: bytes
Server: awex
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff`

I will help you in testing of this.

Can you please share the code you placed in your server.

**Comment by FrancMunoz** [comment]
Hey! Sorry for the delay... I think I found the problem, will update soon.

**Comment by OSapar** [comment]
Okay. I would like know the problem as well.

**Comment by FrancMunoz** [comment]
@OSapar, I did some tests and all worked for me, even from your server. The problem is that you are trying to update a device with an image created for an older firmware. So the call to `Spark_Finish_Firmware_Update`  fails.

To make it work:
1. Create a dummy firmware:

``` c++
/*
 * Project Particle Electron OTA Update Dummy
 * Description: Dummy used to update
 * Author: Franc Muñoz - ZeroWorks!
 * Date: 23/08/2019
 */

// We only need internet connection...
SYSTEM_MODE(SEMI_AUTOMATIC);

void setup() {
    Serial.begin();
    delay(2000);
    Serial.println("Device UPDATED!");
}

int ms=0;
bool once=true;

void loop() {
    // Wait 5 seconds... don't needed at all... but gave me some time to start  serial debug
    if(millis()-ms>5000 && once) {
        Serial.println("Device UPDATED!");
        once=false;
    }
}
```
2. Compile, rename it to flash.bin and copy it to your server in the same folder `update/`
3. Compile the OTA firm and flash your device.

The firmware in your server must be compiled for your device... mine (the one the you used) is for an older versión so it won't work.

And it should work.

Could you try it please? And let men know...

**Comment by OSapar** [comment]
Its still not working for me. Before copying the firmware on server i tested it on my device it worked but I am getting error in OTA firmware update. I have uploaded image of above code for Electron v1.2.1. 

I am able OTA update image from your server with Electron v1.2.1.

![image](https://user-images.githubusercontent.com/41289433/63593341-6c75b180-c5d1-11e9-9a72-9570806b7fd8.png)

Did you able to OTA firmware update from my server?

Thank you!

**Comment by FrancMunoz** [comment]
Yes I did from your server using Electron v1.0.1... will upgrade to latest an try...

**Comment by FrancMunoz** [comment]
@OSapar , it works for me @ 1.2.1, I've uptaded `flash.bin` in my server:

Put this file on your server (and let me know I will test too):
[Download flash.bin from my server for 1.2.1](http://www.zeroworks.net/updates/ota/flash.bin)

Use this firmware for 1.2.1:
[Firmware flash.zip for 1.2.1](https://github.com/FrancMunoz/electrontcpfirmflash/files/3534847/flash.zip)

And the results:
![Captura](https://user-images.githubusercontent.com/8903413/63598614-37ad2e80-c5c0-11e9-91e5-51b5c3e9c8a6.JPG)

Tested and working.

**Comment by OSapar** [comment]
Sorry for the delay. I followed all your instructions but still facing the same issue. You can try to download from my server. I think this is the issue with server. I think both firmware links are pointing to same flash.bin file. Can you please check this as well.

**Comment by FrancMunoz** [comment]
I dumped downloaded data from both server and it's the same. I've noticed some differences in downloaded chunks (they have different sizes) so have to investigate whether `Spark_Save_Firmware_Chunk` have any issue about that chunk sizes or not. 

Also I investigated what means error code 1 returned by `Spark_Finish_Firmware_Update`. It seems that downloaded data from your server does not pass `HAL_FLASH_OTA_Validate` validation or fails in `HAL_FLASH_End` both internal calls.

Finally, have to check if headers has something that affects the download... All in all doesn't seems any related with script but server config. I tried in different servers and it worked.

Meanwhile, I guess if you put my server in your script it works... could you please confirm?

**Comment by OSapar** [comment]
Yes,  if I put your server in script it works. It doesn't seem that differences in downloaded chunks affecting this, because from your server also chunk size was almost same.

![image](https://user-images.githubusercontent.com/41289433/63748742-94159400-c8c7-11e9-82f4-35bbbc824473.png)

I tried with different server but facing the same issue.

**Comment by FrancMunoz** [comment]
Well, the first chunk from your server is only 51 bytes, from mine is 96... and the dumps are identical, the script calls `Spark_Save_Firmware_Chunk`... the rest of chunks are 128 bytes length from both servers... and the last one of course is different size. Since hex dumps are identical I think we have to consider all calls in the process that leads to fail.

All in all, is it possible to give me FTP access to one folder in your server?

**Comment by OSapar** [comment]
@FrancMunoz  I sent you details in email. Please check and let me know the issue.

**Comment by FrancMunoz** [comment]
Got it! The chunks have to be aligned... I guess when `Spark_Save_Firmware_Chunk` is called the number of bytes has to be even.  The first chunk sent from your server used to be odd.

I forced chunks to be 512 bytes length but last one.

I'm preparing the commit.

**Comment by OSapar** [comment]
Thanks a lot!! Now its working.

**Comment by FrancMunoz** [comment]
You're welcome!
